version: '3.7'
services:

  python:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    container_name: python
    ports:
      - 5000:5000

